# [Spring 설정]
spring:
  profiles: 
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
        url: jdbc:mysql://127.0.0.1:3306/mservice?useUnicode=true&characterEncoding=UTF-8
        username: root 
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver    
  
# [Context 설정]
server:
  port: 8080
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development: true
        
        
